# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup SSH
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.0.1
      with:
        # Private key required to access the host
        ssh-private-key: ${{ secrets.SECRET_KEY }}
        # Hostname or IP to add to the known hosts file
        ssh-host: 134.122.124.102
    - name: Teste
      run: |
        ssh root@134.122.124.102 bash -c "docker-compose down \
        bash create-docker-compose.sh docker.pkg.github.com/${{ github.repository }}/cyoa-server:${{ github.sha }}"
        


        
